Implement authentication with OpenSSH user certificate from file
mwiede/jsch pull request #242
Opened 2022-11-21 08:06 UTC by lovish1999

2022-11-21 09:13 UTC, mwiede commented
hi @lovish1999 I know there are no contribution guidelines in this repo, but can you at least put a few words and links about what you have implemented?

2022-11-21 09:19 UTC, mwiede commented
@lovish1999 have you seen how tests are implemented in this project? (https://github.com/mwiede/jsch/blob/master/src/test/java/com/jcraft/jsch/Algorithms2IT.java) 
It would be nice, if you could provide tests for new functionality. Thanks

2022-11-21 11:10 UTC, lovish1999 commented
Hi @mwiede , sorry I was just testing it first so could not update. Basically I have tried to add support for OpenSSH certificates as done in [is/jsch](https://github.com/is/jsch). I see this was raised here earlier #31. Once I complete the testing, will update here. Also, I will try to create the tests then for this.

2022-11-21 11:42 UTC, norrisjeremy commented
I don't think this should be merged unless at the very least support for `HostCertificates` is implemented as well (as I noted in https://github.com/mwiede/jsch/issues/31#issuecomment-911968703).

2022-11-21 11:56 UTC, norrisjeremy requested changes

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/KeyPair.java
> -  public static final int UNKNOWN=4;
This should be reverted (`UNKNOWN` should continue to have a value of `4`).

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/KeyPair.java
> +  public static final int ECDSA_CERT = 9;
Missing support for `ED25519_CERT` & `ED448_CERT`.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/KeyPair.java
> +                }
It would be nice to maintain the existing coding style here (namely no spaces surrounding `=`, `==`, etc.).

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/KeyPair.java
> +                }
It would be nice to maintain the existing coding style here (namely no spaces surrounding `=`, `==`, etc.).

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/KeyPair.java
> -              if(prvkey==null && buf.length>7){
The `prvkey==null` check here appears to have been lost.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHUserCertDSA.java
> +    public int getCertificateType() {
Missing `@Override` annotation.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHUserCertECDSA.java
> +    public int getCertificateType() {
Missing `@Override` annotation.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHUserCertRSA.java
> +    public int getCertificateType() {
Missing `@Override` annotation.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHUserCertDSA.java
> +public class OpenSSHUserCertDSA extends KeyPairDSA implements OpenSSHCertifiedKey {
This class should be package-private, not public.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHUserCertECDSA.java
> +public class OpenSSHUserCertECDSA extends KeyPairECDSA implements OpenSSHCertifiedKey {
This class should be package-private, not public.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHUserCertRSA.java
> +public class OpenSSHUserCertRSA extends KeyPairRSA implements OpenSSHCertifiedKey {
This class should be package-private, not public.

2022-11-21 11:56 UTC, norrisjeremy commented on src/main/java/com/jcraft/jsch/OpenSSHCertifiedKey.java
> +public interface OpenSSHCertifiedKey {
Why do we even need an interface for this?

2022-11-21 11:58 UTC, mwiede commented
Link to spec: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.certkeys

2022-12-06 08:52 UTC, lovish1999 commented
@norrisjeremy looks like this addition will require many more changes. I am closing the pull request for now. Thanks !

2022-12-06 08:52 UTC, closed without merging